services:
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes

  api:
    container_name: api
    build: .
    volumes:
      - .:/app
    command: fastapi dev src/main.py --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - API_KEYS=${API_KEYS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    
  task-worker:
    container_name: task-worker
    build: .
    command: watchfiles --filter python "celery --app=src.celery.celery_app worker --concurrency=2 --loglevel=INFO" src
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - API_KEYS=${API_KEYS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  task-monitor:
    container_name: task-monitor
    image: mher/flower:latest
    command: celery --broker=redis://redis:6379/0 flower
    ports:
      - "127.0.0.1:5555:5555"
    depends_on:
      - redis
    environment:
      - FLOWER_UNAUTHENTICATED_API=true

volumes:
  redis-data: